apiVersion: mcp/v1beta1
kind: MCPServer
metadata:
  name: lightspeed-mcp-server
  title: Red Hat Lightspeed MCP Server
  namespace: redhat

  description: An MCP server to enable AI agents to query platform data, analyze systems, identify critical vulnerabilities, and perform proactive planning and lifecycle management.

  tags:
    - mcp
    - lightspeed
    - administration

  links:
    - url: https://catalog.redhat.com/en/software/container-stacks/detail/69441d9d0df8059c340fa3f1
      title: View on Red Hat Catalog
      type: documentation

spec:
  type: local
  lifecycle: developer-preview
  owner: group:redhat/rh-lightspeed-mcp

  packages:
    - type: container
      registry: quay.io
      name: redhat-services-prod/insights-management-tenant/insights-mcp/red-hat-lightspeed-mcp
      version: latest
    - type: container
      registry: ghcr.io
      name: redhatinsights/red-hat-lightspeed-mcp
      version: latest
