site_name: Red Hat Lightspeed MCP Server
docs_dir: docs/mkdocs
nav:
  - Home: index.md
  - Usage: usage.md
  - Hacking: HACKING.md
  - LLM eval harness: mcp-llm-eval.md
  - Toolsets: toolsets.md
plugins:
  - techdocs-core
