"""Unit tests for scripts/patch_generated_cli.py."""

from pathlib import Path

from scripts.patch_generated_cli import patch_generated_cli

SAMPLE = '''\
#!/usr/bin/env python3
"""CLI for server_cli MCP server.

Generated by: fastmcp generate-cli example
"""

import json
from fastmcp.client.transports import StdioTransport
from rich.console import Console

CLIENT_SPEC = StdioTransport(command='fastmcp', args=['run', '/tmp/server_cli.py', '--no-banner'])
app = cyclopts.App(name="server_cli", help="CLI for server_cli MCP server")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


@app.command
async def list_tools() -> None:
    """List available tools."""
    pass


@app.command
async def list_resources() -> None:
    """List available resources."""
    pass
'''


def test_patch_generated_cli_replaces_transport_and_name(tmp_path: Path):
    """patch_generated_cli rewrites CLIENT_SPEC and cyclopts app name for insights brand."""
    path = tmp_path / "cli.py"
    path.write_text(SAMPLE, encoding="utf-8")
    patch_generated_cli(path, brand="insights")
    text = path.read_text(encoding="utf-8")
    assert "build_stdio_client_spec" in text
    assert "def client_spec():" in text
    assert "Client(client_spec())" in text or "client_spec()" in text
    assert "CLIENT_SPEC = StdioTransport" not in text
    assert 'name="insights-mcp-cli"' in text
    assert "version=_CLI_VERSION" in text
    assert "help_prologue=_HELP_PROLOGUE" in text
    assert "run_list_tools" in text
    assert "/tmp/server_cli.py" not in text
