"""Unit tests for scripts/patch_generated_cli.py."""

from pathlib import Path

from scripts.patch_generated_cli import patch_generated_cli

SAMPLE = '''\
#!/usr/bin/env python3
"""CLI for server_cli MCP server.

Generated by: fastmcp generate-cli example
"""

import json
from fastmcp.client.transports import StdioTransport

CLIENT_SPEC = StdioTransport(command='fastmcp', args=['run', '/tmp/server_cli.py', '--no-banner'])
app = cyclopts.App(name="server_cli", help="CLI for server_cli MCP server")
'''


def test_patch_generated_cli_replaces_transport_and_name(tmp_path: Path):
    """patch_generated_cli rewrites CLIENT_SPEC and cyclopts app name for insights brand."""
    path = tmp_path / "cli.py"
    path.write_text(SAMPLE, encoding="utf-8")
    patch_generated_cli(path, brand="insights")
    text = path.read_text(encoding="utf-8")
    assert "import os" in text
    assert "INSIGHTS_MCP_SERVER_CMD" in text
    assert 'name="insights-mcp-cli"' in text
    assert "/tmp/server_cli.py" not in text
