#!/usr/bin/env python3
"""Generate SVG diagrams from Mermaid source in HACKING.md.

This script extracts Mermaid code blocks from HACKING.md and generates
SVG images using Podman with the Mermaid CLI container.
"""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


def extract_mermaid_blocks(markdown_file: Path) -> dict[str, str]:
    """Extract Mermaid code blocks from markdown file.

    Args:
        markdown_file: Path to the markdown file

    Returns:
        Dictionary mapping diagram names to Mermaid source code
    """
    content = markdown_file.read_text(encoding="utf-8")
    mermaid_blocks = {}

    # Pattern to match Mermaid code blocks with optional title
    pattern = r"```mermaid\n(.*?)```"
    matches = re.finditer(pattern, content, re.DOTALL)

    for i, match in enumerate(matches):
        mermaid_code = match.group(1).strip()

        # Extract diagram name from title comment: %% title: diagram-name
        title_pattern = r"%%\s*title:\s*([^\n]+)"
        title_match = re.search(title_pattern, mermaid_code, re.IGNORECASE)
        if not title_match:
            print(
                f"Error: Mermaid diagram {i + 1} is missing '%% title: diagram-name' comment",
                file=sys.stderr,
            )
            sys.exit(1)

        diagram_name = title_match.group(1).strip()
        if not diagram_name:
            print(
                f"Error: Mermaid diagram {i + 1} has empty title in '%% title:' comment",
                file=sys.stderr,
            )
            sys.exit(1)

        mermaid_blocks[diagram_name] = mermaid_code

    return mermaid_blocks


def check_podman() -> bool:
    """Check if podman is available.

    Returns:
        True if podman is available, False otherwise
    """
    return shutil.which("podman") is not None


def generate_svg_from_mermaid(mermaid_code: str, output_file: Path, docs_dir: Path) -> None:
    """Generate SVG from Mermaid code using Podman with Mermaid CLI container.

    Args:
        mermaid_code: Mermaid diagram source code
        output_file: Path where the SVG file should be written
        docs_dir: Directory containing docs (used for podman mount)

    Raises:
        subprocess.CalledProcessError: If podman command fails
        FileNotFoundError: If podman is not available
    """
    if not check_podman():
        raise FileNotFoundError("podman is not available. Please install podman to generate diagrams.")

    # Write input file directly to docs directory
    input_file = docs_dir / "input.mmd"
    input_file.write_text(mermaid_code, encoding="utf-8")

    # Use official Mermaid CLI container
    container_image = "ghcr.io/mermaid-js/mermaid-cli/mermaid-cli:latest"

    # Run podman to convert Mermaid to SVG
    # Mount docs_dir as both /data (for input) and /output (for output)
    docs_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        "podman",
        "run",
        "--rm",
        "--userns=keep-id",
        f"--user={os.getuid()}",
        "-v",
        f"{docs_dir.absolute()}:/data:Z",
        container_image,
        "-i",
        "/data/input.mmd",
        "-o",
        f"/data/{output_file.name}",
    ]

    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)

        # Post-process SVG to make box border match background color
        # This makes the border effectively invisible
        if output_file.exists():
            _make_box_border_match_background(output_file, rgb_color=(225, 245, 255))
    except subprocess.CalledProcessError as e:
        error_msg = f"Failed to generate SVG: {e.stderr if e.stderr else e.stdout}"
        raise RuntimeError(error_msg) from e
    finally:
        # Clean up input file
        if input_file.exists():
            input_file.unlink()


def _make_box_border_match_background(svg_file: Path, rgb_color: tuple[int, int, int]) -> None:
    """Post-process SVG to make box border color match background color.

    This is a workaround to make the box border color match the background color.
    The SVG generated by Mermaid CLI has a border color that is not the same as the background color.
    This is a workaround to make the border color match the background color
    as there is no way to set the border color in the Mermaid code or remove the border completely.

    Args:
        svg_file: Path to the SVG file to modify
        rgb_color: RGB tuple (r, g, b) representing the background color
    """
    try:
        # Read SVG as text for easier manipulation
        content = svg_file.read_text(encoding="utf-8")

        # Convert RGB to hex color
        hex_color = f"#{rgb_color[0]:02x}{rgb_color[1]:02x}{rgb_color[2]:02x}"
        rgb_str = f"rgb({rgb_color[0]}, {rgb_color[1]}, {rgb_color[2]})"

        # Find rect elements with our background color and update their stroke
        # Pattern: rect with fill="rgb(225, 245, 255)" and stroke="..."
        pattern = rf'(<[^>]*rect[^>]*fill=["\']?{re.escape(rgb_str)}["\']?[^>]*stroke=["\']?)([^"\'>]+)(["\']?[^>]*>)'

        def replace_stroke(match):
            return f"{match.group(1)}{hex_color}{match.group(3)}"

        content = re.sub(pattern, replace_stroke, content)

        # Also handle stroke in style attributes
        # Pattern: style="...stroke:rgb(...)..."
        style_pattern = r'(style=["\'])([^"\']*stroke:\s*)[^;)]+([;"\'])'

        def replace_style_stroke(match):
            return f"{match.group(1)}{match.group(2)}{hex_color}{match.group(3)}"

        content = re.sub(style_pattern, replace_style_stroke, content)

        # Ensure file ends with newline (pre-commit requirement)
        if not content.endswith("\n"):
            content += "\n"

        # Write modified SVG
        svg_file.write_text(content, encoding="utf-8")
    except Exception as e:
        # If post-processing fails, just log and continue with original SVG
        print(f"Warning: Could not post-process SVG border color: {e}", file=sys.stderr)


def main():
    """Main function to generate diagrams."""
    # Get project root directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    hacking_md = project_root / "HACKING.md"
    docs_dir = project_root / "docs"

    if not hacking_md.exists():
        print(f"Error: {hacking_md} not found", file=sys.stderr)
        sys.exit(1)

    # Create docs directory if it doesn't exist
    docs_dir.mkdir(exist_ok=True)

    # Extract Mermaid blocks
    mermaid_blocks = extract_mermaid_blocks(hacking_md)

    if not mermaid_blocks:
        print("No Mermaid diagrams found in HACKING.md", file=sys.stderr)
        sys.exit(1)

    # Check if podman is available
    if not check_podman():
        print(
            "Error: podman is not available. Please install podman to generate diagrams.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Generate SVG files
    for diagram_name, mermaid_code in mermaid_blocks.items():
        print(f"Generating {diagram_name}.svg...")
        try:
            svg_file = docs_dir / f"{diagram_name}.svg"
            generate_svg_from_mermaid(mermaid_code, svg_file, docs_dir)
            print(f"✓ Saved to {svg_file}")
        except (FileNotFoundError, RuntimeError) as e:
            print(f"✗ Error: {e}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
