#!/usr/bin/env python3
"""Post-process fastmcp generate-cli output for portable, brand-aware transport."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_BRAND_SERVER_CMD = {
    "insights": "insights-mcp",
    "red-hat-lightspeed": "red-hat-lightspeed-mcp",
}

_BRAND_CLI_NAME = {
    "insights": "insights-mcp-cli",
    "red-hat-lightspeed": "red-hat-lightspeed-mcp-cli",
}

_CLIENT_SPEC_BLOCK = """\
_BRAND_SERVER_CMD = {
    "insights": "insights-mcp",
    "red-hat-lightspeed": "red-hat-lightspeed-mcp",
}


def _default_server_cmd() -> str:
    brand = os.environ.get("CONTAINER_BRAND", "{brand}")
    return _BRAND_SERVER_CMD.get(brand, _BRAND_SERVER_CMD["insights"])


_CLIENT_CMD = os.environ.get("INSIGHTS_MCP_SERVER_CMD") or _default_server_cmd()
_CLIENT_ARGS = os.environ.get("INSIGHTS_MCP_SERVER_ARGS", "stdio").split()
CLIENT_SPEC = StdioTransport(command=_CLIENT_CMD, args=_CLIENT_ARGS)
"""


def patch_generated_cli(path: Path, *, brand: str) -> None:
    if brand not in _BRAND_SERVER_CMD:
        raise ValueError(f"invalid brand: {brand!r}, want one of {sorted(_BRAND_SERVER_CMD)}")

    text = path.read_text(encoding="utf-8")
    cli_name = _BRAND_CLI_NAME[brand]

    if "import os\n" not in text and "import os\r\n" not in text:
        text = text.replace("import json\n", "import json\nimport os\n", 1)

    text = re.sub(
        r"^CLIENT_SPEC = StdioTransport\(.*\)\s*$",
        _CLIENT_SPEC_BLOCK.replace("{brand}", brand).rstrip(),
        text,
        count=1,
        flags=re.MULTILINE,
    )

    text = re.sub(
        r'app = cyclopts\.App\(name="[^"]*"',
        f'app = cyclopts.App(name="{cli_name}"',
        text,
        count=1,
    )

    doc_pattern = re.compile(
        r'^"""CLI for server_cli MCP server\.\s*\n\s*Generated by:.*?\n"""',
        re.MULTILINE | re.DOTALL,
    )
    replacement = (
        f'"""CLI for {cli_name} (spawns {_BRAND_SERVER_CMD[brand]} over stdio).\n\n'
        f'Generated by: fastmcp generate-cli (patched for {brand}).\n"""'
    )
    text = doc_pattern.sub(replacement, text, count=1)

    path.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Patch fastmcp generate-cli output.")
    parser.add_argument("path", type=Path, help="Path to generated CLI Python file")
    parser.add_argument(
        "--brand",
        required=True,
        choices=sorted(_BRAND_SERVER_CMD),
        help="Container brand (insights or red-hat-lightspeed)",
    )
    args = parser.parse_args()
    if not args.path.is_file():
        print(f"file not found: {args.path}", file=sys.stderr)
        sys.exit(1)
    patch_generated_cli(args.path, brand=args.brand)


if __name__ == "__main__":
    main()
