#!/usr/bin/env python3
"""Post-process fastmcp generate-cli output for portable, brand-aware transport."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_BRAND_SERVER_CMD = {
    "insights": "insights-mcp",
    "red-hat-lightspeed": "red-hat-lightspeed-mcp",
}

_BRAND_CLI_NAME = {
    "insights": "insights-mcp-cli",
    "red-hat-lightspeed": "red-hat-lightspeed-mcp-cli",
}

_CATALOG_IMPORTS_BLOCK = """\
from insights_mcp.cli_catalog import catalog_help_prologue, mcp_package_version
from insights_mcp.cli_list_tools import run_list_tools
from insights_mcp.cli_transport import build_stdio_client_spec

_CLI_VERSION = mcp_package_version()
_HELP_PROLOGUE = catalog_help_prologue()


def client_spec():
    return build_stdio_client_spec()
"""

_LIST_TOOLS_REPLACEMENT = '''\
@app.command
async def list_tools() -> None:
    """List tools currently enabled on the MCP server (see help for disabled write tools)."""
    await run_list_tools(console, client_spec())
'''

# Legacy static transport block (pre client_spec patch)
_LEGACY_CLIENT_SPEC_BLOCK = re.compile(
    r"_BRAND_SERVER_CMD = \{.*?\n\nCLIENT_SPEC = StdioTransport\(.*?\)\n",
    re.DOTALL,
)

_SIMPLE_CLIENT_SPEC_LINE = re.compile(
    r"^CLIENT_SPEC = StdioTransport\(.*\)\s*\n",
    re.MULTILINE,
)

_APP_LINE_PATTERN = re.compile(
    r'^app = cyclopts\.App\(name="[^"]*", help="[^"]*"\)\s*$',
    re.MULTILINE,
)

_LIST_TOOLS_PATTERN = re.compile(
    r"@app\.command\nasync def list_tools\(\) -> None:.*?(?=\n@app\.command|\n@call_tool_app\.command|\Z)",
    re.DOTALL,
)


def patch_generated_cli(path: Path, *, brand: str) -> None:
    """Apply brand-aware transport and catalog patches to a generated CLI file."""
    if brand not in _BRAND_SERVER_CMD:
        raise ValueError(f"invalid brand: {brand!r}, want one of {sorted(_BRAND_SERVER_CMD)}")

    text = path.read_text(encoding="utf-8")
    cli_name = _BRAND_CLI_NAME[brand]
    server_cmd = _BRAND_SERVER_CMD[brand]

    if "from insights_mcp.cli_catalog import" not in text:
        text = text.replace(
            "from fastmcp.client.transports import StdioTransport\n",
            "from fastmcp.client.transports import StdioTransport\n" + _CATALOG_IMPORTS_BLOCK,
            1,
        )
    elif "from insights_mcp.cli_transport import build_stdio_client_spec" not in text:
        text = text.replace(
            "from insights_mcp.cli_list_tools import run_list_tools\n",
            "from insights_mcp.cli_list_tools import run_list_tools\n"
            "from insights_mcp.cli_transport import build_stdio_client_spec\n\n\n"
            "def client_spec():\n"
            "    return build_stdio_client_spec()\n",
            1,
        )

    text, _ = _LEGACY_CLIENT_SPEC_BLOCK.subn("", text, count=1)
    text, _ = _SIMPLE_CLIENT_SPEC_LINE.subn("", text)

    if "def client_spec():" not in text:
        raise ValueError(f"expected client_spec() after patch in {path}")

    text = text.replace("Client(CLIENT_SPEC)", "Client(client_spec())")

    app_replacement = (
        f"app = cyclopts.App(\n"
        f'    name="{cli_name}",\n'
        f'    help="CLI for {server_cmd} MCP server (spawns server over stdio)",\n'
        f"    version=_CLI_VERSION,\n"
        f"    help_prologue=_HELP_PROLOGUE,\n"
        f")"
    )
    text, app_count = _APP_LINE_PATTERN.subn(app_replacement, text, count=1)
    if app_count != 1:
        raise ValueError(f"expected to patch one cyclopts.App line in {path}, got {app_count}")

    text, list_count = _LIST_TOOLS_PATTERN.subn(_LIST_TOOLS_REPLACEMENT.strip() + "\n\n", text, count=1)
    if list_count != 1:
        raise ValueError(f"expected to patch list_tools in {path}, got {list_count}")

    doc_pattern = re.compile(
        r'^"""CLI for server_cli MCP server\.\s*\n\s*Generated by:.*?\n"""',
        re.MULTILINE | re.DOTALL,
    )
    replacement = (
        f'"""CLI for {cli_name} (spawns {server_cmd} over stdio).\n\n'
        f'Generated by: fastmcp generate-cli (patched for {brand}).\n"""'
    )
    text = doc_pattern.sub(replacement, text, count=1)

    path.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Patch fastmcp generate-cli output.")
    parser.add_argument("path", type=Path, help="Path to generated CLI Python file")
    parser.add_argument(
        "--brand",
        required=True,
        choices=sorted(_BRAND_SERVER_CMD),
        help="Container brand (insights or red-hat-lightspeed)",
    )
    args = parser.parse_args()
    if not args.path.is_file():
        print(f"file not found: {args.path}", file=sys.stderr)
        sys.exit(1)
    patch_generated_cli(args.path, brand=args.brand)


if __name__ == "__main__":
    main()
