name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          sudo apt install -y aspell

      - name: Run lint
        run: make lint

      - name: Fail if there are changed files
        run: |
          if git diff --name-only | grep .; then
            echo "Error: there are changed files after linting"
            echo "Please run 'make lint' and commit the changes"
            exit 1
          fi
